# Generated by Django 2.2.4 on 2020-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0028_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pump_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
