# Generated by Django 2.2.4 on 2020-10-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0031_car_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
