# Generated by Django 2.2.4 on 2020-10-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0033_auto_20201008_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
