# Generated by Django 2.2.4 on 2020-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0036_featured_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
