# Generated by Django 2.2.4 on 2020-10-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0037_car_seller_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='package',
            field=models.TextField(blank=True, null=True),
        ),
    ]
