# Generated by Django 2.2.4 on 2020-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0038_car_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
