# Generated by Django 2.2.4 on 2020-10-11 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0039_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
