# Generated by Django 2.2.4 on 2020-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0044_clearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trials',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
