# Generated by Django 2.2.4 on 2020-10-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0045_userprofile_trials'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
