# Generated by Django 2.2.4 on 2020-10-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0048_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
