# Generated by Django 2.2.4 on 2020-10-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0050_car_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('make', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('service', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
