# Generated by Django 2.2.4 on 2020-10-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0051_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
