# Generated by Django 2.2.4 on 2020-11-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0055_auto_20201114_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Dealer', 'Dealer'), ('Buyer', 'Buyer'), ('Seller', 'Seller'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
