# Generated by Django 2.2.4 on 2020-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0056_auto_20201120_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dealer_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
