# Generated by Django 2.2.4 on 2020-11-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0057_auto_20201120_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dealer_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='premium_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
