# Generated by Django 2.2.4 on 2020-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0058_auto_20201120_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='feature_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
