# Generated by Django 2.2.4 on 2020-11-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0059_auto_20201120_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
