# Generated by Django 2.2.4 on 2020-12-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0060_auto_20201124_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
